db_connection_str: '**********'
db_name: dev_db
from_address: test@test.com
generate_correlation_id: true
html_email_template: '<!DOCTYPE html><html><head></head><body style="color: #00393f;padding:
  12px;"><h2>Dear $recipient_name,</h2><p>$plaintext_body</p><p>Warm regards,</p><h3>The
  GHGA Team</h3></body></html>'
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: INFO
log_traceback: true
login_password: '**********'
login_user: test@test.com
notification_event_topic: notifications
notification_event_type: notification
plaintext_email_template: 'Dear $recipient_name,


  $plaintext_body


  Warm regards,


  The GHGA Team'
service_instance_id: '001'
service_name: ns
smtp_host: 127.0.0.1
smtp_port: 587
use_starttls: false
