# Please only mention the non-default settings here:

notification_topic: notifications
notification_type: notification
service_instance_id: "001"
kafka_servers: ["kafka:9092"]
kafka_enable_dlq: True
plaintext_email_template: "Dear $recipient_name,\n\n$plaintext_body\n\nWarm regards,\n\nThe GHGA Team"
html_email_template: '<!DOCTYPE html><html><head></head><body style="color: #00393f;padding: 12px;"><h2>Dear $recipient_name,</h2><p>$plaintext_body</p><p>Warm regards,</p><h3>The GHGA Team</h3></body></html>'
smtp_host: 127.0.0.1
smtp_port: 587
smtp_auth:
  username: "test@test.com"
  password: test
from_address: "test@test.com"
use_starttls: false
mongo_dsn: "mongodb://mongodb:27017"
db_name: "dev_db"
migration_wait_sec: 10
db_version_collection: nsDbVersions

otel_exporter_endpoint: http://localhost:4318
