[project]
name = "ns"
version = "3.0.2"
description = "The Notification Service (NS) handles notification kafka events."
dependencies = [
    "typer>=0.12",
    "ghga-event-schemas>=4.1, < 5",
    "ghga-service-commons>=3.3",
    "hexkit[akafka,mongodb]>=4",
]

[project.urls]
Repository = "https://github.com/ghga-de/notification-service"

[project.scripts]
ns = "ns.__main__:run"
