[project]
name = "ns"
version = "5.0.0"
description = "The Notification Service (NS) handles notification kafka events."
dependencies = [
    "typer>=0.15",
    "ghga-event-schemas>=10, < 11",
    "ghga-service-commons>=4.2",
    "hexkit[akafka,mongodb,opentelemetry]>=6",
]

[project.urls]
Repository = "https://github.com/ghga-de/notification-service"

[project.scripts]
ns = "ns.__main__:run"
