[project]
name = "ns"
version = "2.0.0"
description = "The Notification Service (NS) handles notification kafka events."
dependencies = [
    "typer>=0.12",
    "ghga-event-schemas>=3.0.0, <4",
    "ghga-service-commons>=3.0.0",
    "hexkit[akafka,mongodb]>=3.0.0",
]

[project.urls]
Repository = "https://github.com/ghga-de/notification-service"

[project.scripts]
ns = "ns.__main__:run"
