[project]
name = "ns"
version = "7.0.0"
description = "The Notification Service (NS) handles notification kafka events."
dependencies = [
    "typer>=0.19",
    "ghga-event-schemas~=11.0",
    "ghga-service-commons>=7",
    "hexkit[akafka,mongodb]>=8",
    "httpx>=0.28.1, <1",
]

[project.urls]
Repository = "https://github.com/ghga-de/notification-service"

[project.scripts]
ns = "ns.__main__:run"
