[project]
name = "ns"
version = "7.1.0"
description = "The Notification Service (NS) handles notification kafka events."
dependencies = [
    "typer>=0.19",
    "ghga-event-schemas~=11.0",
    "ghga-service-commons>=8",
    "hexkit[akafka,mongodb]>=8",
    "httpx2>=2.9.1, <3",
]

[project.urls]
Repository = "https://github.com/ghga-de/notification-service"

[project.scripts]
ns = "ns.__main__:run"
