[project]
name = "ns"
version = "5.0.1"
description = "The Notification Service (NS) handles notification kafka events."
dependencies = [
    "typer>=0.19",
    "ghga-event-schemas~=10.1",
    "ghga-service-commons>=5.1",
    "hexkit[akafka,mongodb]>=7.1",
]

[project.urls]
Repository = "https://github.com/ghga-de/notification-service"

[project.scripts]
ns = "ns.__main__:run"
